channels:
  - wietsedv
  - huggingface
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.8

  # Base
  - matplotlib
  - notebook
  - numba
  - numpy
  - pandas
  - pyyaml
  - scipy
  - seqeval
  - toml
  - tqdm

  # Dev
  - conda-lock
  - flake8
  - yapf

  # DL Frameworks
  - onnx
  - pytorch=1.8
  - tensorflow=2.4.1

  # Audio
  - dtw-python >=1.1
  - pysoundfile >=0.10
  # - sox >=14.4

  # Frameworks
  - datasets >=1.5
  - fairseq >=0.10
  - nltk >=3.6
  - scikit-learn >=0.24
  - tokenizers >=0.10
  - transformers >=4.5

  # Integration
  - pynvml
  - tensorboardx >=2.2
  - wandb >=0.10

