channels:
  - wietsedv
  - pytorch
  - conda-forge

dependencies:
  - python=3.8
  - pip

  - numpy
  - numba
  - pandas
  - pysoundfile
  - pyyaml
  - pytorch >=1.8
  - scipy
  - tqdm

  - datasets >=1.5
  - dtw-python >=1.1
  - fairseq >=0.10
  - tokenizers >=0.10
  - transformers >=4.5
