channels:
  - wietsedv
  - huggingface
  - pytorch
  - nvidia
  - conda-forge

# TODO Add GitHub Action to update these pins
dependencies:
  - python=3.8.10
  - numpy=1.20.2
  - pytorch=1.8
  - tensorflow=2.4.1

  # Compat
  - blas=2.106
