name: Update lock file

on:
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          pip install conda-lock
          ./update.sh
