name: Update lock file

on:
  push:
    paths:
      - '*.yml'
  schedule:
    - cron: '30 1 * * 0'
  workflow_dispatch:

jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          pip install conda-lock
          ./lock.sh
          if git diff --exit-code; then
              echo "no changes detected. not pusing new lock file"
              exit 0
          fi
          git add .
          git commit -m "update lock files [$(date --iso-8601)]"
          git push origin main
